# Generated by Django 5.1.6 on 2025-02-14 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allModels", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounts",
            name="birthday",
            field=models.DateField(null=True),
        ),
    ]
