# Generated by Django 5.1.6 on 2025-03-06 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allModels", "0002_alter_accounts_birthday"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtworkGenre",
            fields=[
                (
                    "artwork_genre_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("artwork_genre", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Artwork Genre",
                "verbose_name_plural": "Artwork Genres",
                "db_table": "Artwork_Genre",
            },
        ),
        migrations.CreateModel(
            name="ArtworkType",
            fields=[
                (
                    "artwork_type_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("artwork_type", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Artwork Type",
                "verbose_name_plural": "Artwork Types",
                "db_table": "Artwork_Type",
            },
        ),
        migrations.CreateModel(
            name="Books",
            fields=[
                ("book_id", models.AutoField(primary_key=True, serialize=False)),
                ("book_name", models.CharField(max_length=255)),
                ("book_release_year", models.DateTimeField()),
                ("book_description", models.TextField()),
                ("book_writer", models.CharField(max_length=255)),
                ("book_country", models.CharField(max_length=255)),
                ("book_publisher", models.CharField(max_length=255)),
                ("book_isbn", models.CharField(max_length=255)),
                ("book_rating_count", models.PositiveIntegerField(default=0)),
                ("book_average_rate", models.JSONField(blank=True, default=dict)),
                (
                    "book_genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="allModels.artworkgenre",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="allModels.artworktype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
                "db_table": "Books",
            },
        ),
        migrations.CreateModel(
            name="Movies",
            fields=[
                ("movie_id", models.AutoField(primary_key=True, serialize=False)),
                ("movie_name", models.CharField(max_length=255)),
                ("movie_release_year", models.DateTimeField()),
                ("movie_description", models.TextField()),
                ("movie_director", models.CharField(max_length=255)),
                ("movie_actors", models.TextField()),
                ("movie_country", models.CharField(max_length=255)),
                ("movie_runtime", models.IntegerField()),
                ("movie_imdb", models.CharField(max_length=255)),
                ("movie_rating_count", models.PositiveIntegerField(default=0)),
                ("movie_average_rate", models.JSONField(blank=True, default=dict)),
                (
                    "movie_genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="allModels.artworkgenre",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="allModels.artworktype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movie",
                "verbose_name_plural": "Movies",
                "db_table": "Movies",
            },
        ),
        migrations.CreateModel(
            name="TvShows",
            fields=[
                ("tvshow_id", models.AutoField(primary_key=True, serialize=False)),
                ("tvshow_name", models.CharField(max_length=255)),
                ("tvshow_release_year", models.DateTimeField()),
                ("tvshow_description", models.TextField()),
                ("tvshow_writer", models.CharField(max_length=255)),
                ("tvshow_country", models.CharField(max_length=255)),
                ("tvshow_publisher", models.CharField(max_length=255)),
                ("tvshow_imdb", models.CharField(max_length=255)),
                ("tvshow_rating_count", models.PositiveIntegerField(default=0)),
                ("tvshow_average_rate", models.JSONField(blank=True, default=dict)),
                (
                    "tvshow_genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="allModels.artworkgenre",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="allModels.artworktype",
                    ),
                ),
            ],
            options={
                "verbose_name": "TvShow",
                "verbose_name_plural": "TvShows",
                "db_table": "TvShows",
            },
        ),
    ]
