# Generated by Django 5.1.6 on 2025-03-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allModels", "0003_artworkgenre_artworktype_books_movies_tvshows"),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="book_cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="movies",
            name="movie_cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="tvshows",
            name="tvshow_cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
