# Generated by Django 5.1.6 on 2025-03-06 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allModels", "0004_books_book_cover_image_movies_movie_cover_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="books",
            name="book_release_year",
        ),
        migrations.RemoveField(
            model_name="tvshows",
            name="tvshow_release_year",
        ),
        migrations.AddField(
            model_name="books",
            name="movie_release_year",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tvshows",
            name="movie_release_year",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movies",
            name="movie_release_year",
            field=models.DateField(blank=True, null=True),
        ),
    ]
