# Generated by Django 5.1.6 on 2025-03-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allModels", "0005_remove_books_book_release_year_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tvshows",
            name="tvshow_genre",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="books",
            name="book_genre",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="movies",
            name="movie_genre",
            field=models.CharField(max_length=255),
        ),
        migrations.RenameField(
            model_name="books",
            old_name="movie_release_year",
            new_name="book_release_year",
        ),
        migrations.RenameField(
            model_name="tvshows",
            old_name="movie_release_year",
            new_name="tvshow_release_year",
        ),
        migrations.DeleteModel(
            name="ArtworkGenre",
        ),
    ]
