# Generated by Django 5.1.6 on 2025-03-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "allModels",
            "0006_alter_tvshows_tvshow_genre_alter_books_book_genre_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="books",
            name="book_isbn",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="movies",
            name="movie_imdb",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="tvshows",
            name="tvshow_imdb",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
