# Generated by Django 5.1.6 on 2025-03-08 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("allModels", "0008_reviews"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reviews",
            options={"verbose_name": "Review", "verbose_name_plural": "Reviews"},
        ),
        migrations.RenameField(
            model_name="reviews",
            old_name="object_id",
            new_name="content_id",
        ),
        migrations.AlterModelTable(
            name="reviews",
            table="Reviews",
        ),
    ]
