# Generated by Django 5.1.6 on 2025-03-08 04:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allModels", "0009_alter_reviews_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviews",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
