# Generated by Django 5.1.6 on 2025-03-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allModels", "0010_reviews_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="accounts",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="user_avatar/"),
        ),
    ]
