# Generated by Django 5.1.6 on 2025-03-08 20:31

import allModels.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allModels", "0011_accounts_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounts",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to=allModels.models.user_avatar_upload_to
            ),
        ),
    ]
