# Generated by Django 5.1.6 on 2025-03-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allModels", "0012_alter_accounts_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounts",
            name="bio",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="accounts",
            name="birthday",
            field=models.DateField(blank=True, null=True),
        ),
    ]
