# Generated by Django 5.1.6 on 2025-03-10 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allModels", "0013_alter_accounts_bio_alter_accounts_birthday"),
    ]

    operations = [
        migrations.AddField(
            model_name="accounts",
            name="favorites",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
