# Generated by Django 5.1.6 on 2025-03-10 03:37

import allModels.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allModels", "0014_accounts_favorites"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reviews",
            name="content_id",
        ),
        migrations.RemoveField(
            model_name="reviews",
            name="content_type",
        ),
        migrations.AddField(
            model_name="reviews",
            name="review_content_id",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="reviews",
            name="review_content_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="allModels.artworktype",
            ),
        ),
        migrations.AlterField(
            model_name="accounts",
            name="favorites",
            field=models.JSONField(
                blank=True, default=allModels.models.default_favorites, null=True
            ),
        ),
    ]
