# Generated by Django 5.1.6 on 2025-03-10 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allModels", "0015_remove_reviews_content_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviews",
            name="review_content_id",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="reviews",
            name="review_content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="allModels.artworktype",
            ),
        ),
    ]
