# Generated by Django 5.1.6 on 2025-03-10 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allModels", "0016_alter_reviews_review_content_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviews",
            name="review_content_id",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="reviews",
            name="review_text",
            field=models.TextField(default=1),
        ),
    ]
