# Generated by Django 5.1.6 on 2025-03-10 16:47

import allModels.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allModels", "0017_alter_reviews_review_content_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounts",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="user_avatar/avatar_default.png",
                null=True,
                upload_to=allModels.models.user_avatar_upload_to,
            ),
        ),
    ]
