# Generated by Django 5.1.6 on 2025-03-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allModels", "0019_alter_accounts_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounts",
            name="username",
            field=models.CharField(
                help_text="Required. 25 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=25,
                unique=True,
            ),
        ),
    ]
