# Generated by Django 5.1.6 on 2025-03-12 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allModels", "0020_alter_accounts_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviews",
            name="rating",
            field=models.IntegerField(default=0),
        ),
    ]
