# Generated by Django 5.1.6 on 2025-03-12 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allModels", "0021_reviews_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviews",
            name="rating",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
