# Generated by Django 5.1.6 on 2025-03-12 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allModels", "0022_alter_reviews_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviews",
            name="rating",
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
    ]
