# Generated by Django 5.1.6 on 2025-03-13 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allModels", "0024_alter_reviews_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="accounts",
            name="follower",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="accounts",
            name="following",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
